//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdPetssiter { get; set; }
        public Nullable<int> IdPet { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual Petsitter Petsitter { get; set; }
    }
}
